import xlrd 
import yaml 
import sys 
import sys 
import os 
class ConfigurationReader:
    def __init__(self,conf_file_path):
        self.conf_file_path = conf_file_path 
        with open(os.path.dirname(os.path.realpath(__file__))+'/conf_origin.yaml',encoding='utf-8') as yaml_file:
            self.conf = yaml.safe_load(yaml_file) 
        super().__init__() 
    def run(self):
        self.read_ngspipeline_configuration() 
        self.read_tgspipeline_configuration() 
        return self.conf 
    def read_ngspipeline_configuration(self):
        self.conf['ngs_pipeline']['enable'] = True 
        ngspipeline_sheet = xlrd.open_workbook(self.conf_file_path).sheet_by_name('ngs_analysis_setting') 
        if ngspipeline_sheet.cell_value(2,1) == True:
            self.conf['ngs_pipeline']['preprocessing']['enable'] = True 
        if ngspipeline_sheet.cell_value(4,1) ==True:
            self.conf['ngs_pipeline']['preprocessing']['fastqc']['enable'] = True 
        if ngspipeline_sheet.cell_value(5,1) != '':
            self.conf['ngs_pipeline']['preprocessing']['fastqc']['--casava'] = ngspipeline_sheet.cell_value(5,1)
        if ngspipeline_sheet.cell_value(6,1) != '':
            self.conf['ngs_pipeline']['preprocessing']['fastqc']["--nofilter"] = ngspipeline_sheet.cell_value(6,1)
        if ngspipeline_sheet.cell_value(7,1) != '':
            self.conf['ngs_pipeline']['preprocessing']['fastqc']["--nogroup"] = ngspipeline_sheet.cell_value(7,1)
        if ngspipeline_sheet.cell_value(8,1) != '':
            self.conf['ngs_pipeline']['preprocessing']['fastqc']["-t"] = ngspipeline_sheet.cell_value(8,1)
        if ngspipeline_sheet.cell_value(9,1) != '':
            self.conf['ngs_pipeline']['preprocessing']['fastqc']["-c"] = ngspipeline_sheet.cell_value(9,1)
        if ngspipeline_sheet.cell_value(10,1) != '':
            self.conf['ngs_pipeline']['preprocessing']['fastqc']["-a"] = ngspipeline_sheet.cell_value(10,1)
        if ngspipeline_sheet.cell_value(11,1) != '':
            self.conf['ngs_pipeline']['preprocessing']['fastqc']["-l"] = ngspipeline_sheet.cell_value(11,1)
        if ngspipeline_sheet.cell_value(12,1) != '':
            self.conf['ngs_pipeline']['preprocessing']['fastqc']["-k"] = ngspipeline_sheet.cell_value(12,1)
            
        if ngspipeline_sheet.cell_value(4, 3) == True:
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["enable"] = True
        if ngspipeline_sheet.cell_value(5, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--phred64"] = ngspipeline_sheet.cell_value(4, 3)
        if ngspipeline_sheet.cell_value(6, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-V"] = ngspipeline_sheet.cell_value(5, 3)
        if ngspipeline_sheet.cell_value(7, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-A"] = ngspipeline_sheet.cell_value(6, 3)
        if ngspipeline_sheet.cell_value(8, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--adapter_sequence"] = ngspipeline_sheet.cell_value(7, 3)
        if ngspipeline_sheet.cell_value(9, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--adapter_sequence_r2"] = ngspipeline_sheet.cell_value(8, 3)
        if ngspipeline_sheet.cell_value(10, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--adapter_fasta"] = ngspipeline_sheet.cell_value(9, 3)
        if ngspipeline_sheet.cell_value(11, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--detect_adapter_for_pe"] = ngspipeline_sheet.cell_value(10, 3)
        if ngspipeline_sheet.cell_value(12, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-f"] = ngspipeline_sheet.cell_value(11, 3)
        if ngspipeline_sheet.cell_value(13, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-t"] = ngspipeline_sheet.cell_value(12, 3)
        if ngspipeline_sheet.cell_value(14, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-b"] = ngspipeline_sheet.cell_value(13, 3)
        if ngspipeline_sheet.cell_value(15, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-F"] = ngspipeline_sheet.cell_value(14, 3)
        if ngspipeline_sheet.cell_value(16, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-T"] = ngspipeline_sheet.cell_value(15, 3)
        if ngspipeline_sheet.cell_value(17, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-B"] = ngspipeline_sheet.cell_value(16, 3)
        if ngspipeline_sheet.cell_value(18, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--trim_poly_g"] = ngspipeline_sheet.cell_value(17, 3)
        if ngspipeline_sheet.cell_value(19, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--poly_g_min_len"] = ngspipeline_sheet.cell_value(18, 3)
        if ngspipeline_sheet.cell_value(20, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-G"] = ngspipeline_sheet.cell_value(19, 3)
        if ngspipeline_sheet.cell_value(21, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--trim_poly_x"] = ngspipeline_sheet.cell_value(20, 3)
        if ngspipeline_sheet.cell_value(22, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--poly_x_min_len"] = ngspipeline_sheet.cell_value(21, 3)
        if ngspipeline_sheet.cell_value(23, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--cut_front"] = ngspipeline_sheet.cell_value(22, 3)
        if ngspipeline_sheet.cell_value(24, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--cut_tail"] = ngspipeline_sheet.cell_value(23, 3)
        if ngspipeline_sheet.cell_value(25, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-r"] = ngspipeline_sheet.cell_value(24, 3)
        if ngspipeline_sheet.cell_value(26, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-W"] = ngspipeline_sheet.cell_value(25, 3)
        if ngspipeline_sheet.cell_value(27, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--cut_mean_quality"] = ngspipeline_sheet.cell_value(26, 3)
        if ngspipeline_sheet.cell_value(28, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--cut_front_window_size"] = ngspipeline_sheet.cell_value(27, 3)
        if ngspipeline_sheet.cell_value(29, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--cut_front_mean_quality"] = ngspipeline_sheet.cell_value(28, 3)
        if ngspipeline_sheet.cell_value(30, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--cut_tail_window_size"] = ngspipeline_sheet.cell_value(29, 3)
        if ngspipeline_sheet.cell_value(31, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--cut_tail_mean_quality"] = ngspipeline_sheet.cell_value(30, 3)
        if ngspipeline_sheet.cell_value(32, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--cut_right_window_size"] = ngspipeline_sheet.cell_value(31, 3)
        if ngspipeline_sheet.cell_value(33, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--cut_right_mean_quality"] = ngspipeline_sheet.cell_value(32, 3)
        if ngspipeline_sheet.cell_value(34, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-Q"] = ngspipeline_sheet.cell_value(33, 3)
        if ngspipeline_sheet.cell_value(35, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-q"] = ngspipeline_sheet.cell_value(34, 3)
        if ngspipeline_sheet.cell_value(36, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-u"] = ngspipeline_sheet.cell_value(35, 3)
        if ngspipeline_sheet.cell_value(37, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-n"] = ngspipeline_sheet.cell_value(36, 3)
        if ngspipeline_sheet.cell_value(38, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-e"] = ngspipeline_sheet.cell_value(37, 3)
        if ngspipeline_sheet.cell_value(39, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-L"] = ngspipeline_sheet.cell_value(38, 3)
        if ngspipeline_sheet.cell_value(40, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--length_required"] = ngspipeline_sheet.cell_value(39, 3)
        if ngspipeline_sheet.cell_value(41, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--length_limit"] = ngspipeline_sheet.cell_value(40, 3)
        if ngspipeline_sheet.cell_value(42, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--low_complexity_filter"] = ngspipeline_sheet.cell_value(41, 3)
        if ngspipeline_sheet.cell_value(43, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--complexity_threshold"] = ngspipeline_sheet.cell_value(42, 3)
        if ngspipeline_sheet.cell_value(44, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--filter_by_index1"] = ngspipeline_sheet.cell_value(43, 3)
        if ngspipeline_sheet.cell_value(45, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--filter_by_index2"] = ngspipeline_sheet.cell_value(44, 3)
        if ngspipeline_sheet.cell_value(46, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--filter_by_index_threshold"] = ngspipeline_sheet.cell_value(45, 3)
        if ngspipeline_sheet.cell_value(47, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--correction"] = ngspipeline_sheet.cell_value(46, 3)
        if ngspipeline_sheet.cell_value(48, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--overlap_len_require"] = ngspipeline_sheet.cell_value(47, 3)
        if ngspipeline_sheet.cell_value(49, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--overlap_diff_limit"] = ngspipeline_sheet.cell_value(48, 3)
        if ngspipeline_sheet.cell_value(50, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--overlap_diff_percent_limit"] = ngspipeline_sheet.cell_value(49, 3)
        if ngspipeline_sheet.cell_value(51, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--umi"] = ngspipeline_sheet.cell_value(50, 3)
        if ngspipeline_sheet.cell_value(52, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--umi_loc"] = ngspipeline_sheet.cell_value(51, 3)
        if ngspipeline_sheet.cell_value(53, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--umi_len"] = ngspipeline_sheet.cell_value(52, 3)
        if ngspipeline_sheet.cell_value(54, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--umi_prefix"] = ngspipeline_sheet.cell_value(53, 3)
        if ngspipeline_sheet.cell_value(55, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["--umi_skip"] = ngspipeline_sheet.cell_value(54, 3)
        if ngspipeline_sheet.cell_value(56, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-p"] = ngspipeline_sheet.cell_value(55, 3)
        if ngspipeline_sheet.cell_value(57, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-P"] = ngspipeline_sheet.cell_value(56, 3)
        if ngspipeline_sheet.cell_value(58, 3) != "":
            self.conf['ngs_pipeline']['preprocessing']["fastp"]["-w"] = ngspipeline_sheet.cell_value(57, 3)
            
        if ngspipeline_sheet.cell_value(4, 5) == True:
            self.conf['ngs_pipeline']['preprocessing']["trimmomatic"]["enable"] = True
        if ngspipeline_sheet.cell_value(5, 5) != "":
            self.conf['ngs_pipeline']['preprocessing']["trimmomatic"]["-threads"] = ngspipeline_sheet.cell_value(5, 5)
        if ngspipeline_sheet.cell_value(6, 5) != "":
            self.conf['ngs_pipeline']['preprocessing']["trimmomatic"]["-phred33"] = ngspipeline_sheet.cell_value(6, 5)
        if ngspipeline_sheet.cell_value(7, 5) != "":
            self.conf['ngs_pipeline']['preprocessing']["trimmomatic"]["-phred64"] = ngspipeline_sheet.cell_value(7, 5)
        if ngspipeline_sheet.cell_value(8, 5) != "":
            self.conf['ngs_pipeline']['preprocessing']["trimmomatic"]["-validatePairs"] = ngspipeline_sheet.cell_value(8, 5)
        if ngspipeline_sheet.cell_value(9, 5) != "":
            self.conf['ngs_pipeline']['preprocessing']["trimmomatic"]["ILLUMINACLIP"] = ngspipeline_sheet.cell_value(9, 5)
        if ngspipeline_sheet.cell_value(10, 5) != "":
            self.conf['ngs_pipeline']['preprocessing']["trimmomatic"]["LEADING"] = ngspipeline_sheet.cell_value(10, 5)
        if ngspipeline_sheet.cell_value(11, 5) != "":
            self.conf['ngs_pipeline']['preprocessing']["trimmomatic"]["TRAILING"] = ngspipeline_sheet.cell_value(11, 5)
        if ngspipeline_sheet.cell_value(12, 5) != "":
            self.conf['ngs_pipeline']['preprocessing']["trimmomatic"]["SLIDINGWINDOW"] = str(ngspipeline_sheet.cell_value(12, 5))
        if ngspipeline_sheet.cell_value(13, 5) != "":
            self.conf['ngs_pipeline']['preprocessing']["trimmomatic"]["MINLEN"] = ngspipeline_sheet.cell_value(13, 5)
        
        if ngspipeline_sheet.cell_value(4, 7) == True:
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["enable"] = True
        if ngspipeline_sheet.cell_value(5, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-a"] = ngspipeline_sheet.cell_value(5, 7)
        if ngspipeline_sheet.cell_value(6, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-g"] = ngspipeline_sheet.cell_value(6, 7)
        if ngspipeline_sheet.cell_value(7, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-b"] = ngspipeline_sheet.cell_value(7, 7)
        if ngspipeline_sheet.cell_value(8, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-e"] = ngspipeline_sheet.cell_value(8, 7)
        if ngspipeline_sheet.cell_value(9, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["--no-indels"] = ngspipeline_sheet.cell_value(9, 7)
        if ngspipeline_sheet.cell_value(10, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-n"] = ngspipeline_sheet.cell_value(10, 7)
        if ngspipeline_sheet.cell_value(11, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-O"] = ngspipeline_sheet.cell_value(11, 7)
        if ngspipeline_sheet.cell_value(12, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["--match-read-wildcards"] = ngspipeline_sheet.cell_value(12, 7)
        if ngspipeline_sheet.cell_value(13, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-N"] = ngspipeline_sheet.cell_value(13, 7)
        if ngspipeline_sheet.cell_value(14, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-u"] = ngspipeline_sheet.cell_value(14, 7)
        if ngspipeline_sheet.cell_value(15, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["--nextseq-trim"] = ngspipeline_sheet.cell_value(15, 7)
        if ngspipeline_sheet.cell_value(16, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-q"] = ngspipeline_sheet.cell_value(16, 7)
        if ngspipeline_sheet.cell_value(17, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["--quality-base"] = ngspipeline_sheet.cell_value(17, 7)
        if ngspipeline_sheet.cell_value(18, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["--length"] = ngspipeline_sheet.cell_value(18, 7)
        if ngspipeline_sheet.cell_value(19, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["--trim-n"] = ngspipeline_sheet.cell_value(19, 7)
        if ngspipeline_sheet.cell_value(20, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["--length-tag"] = ngspipeline_sheet.cell_value(20, 7)
        if ngspipeline_sheet.cell_value(21, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["--strip-suffix"] = ngspipeline_sheet.cell_value(21, 7)
        if ngspipeline_sheet.cell_value(22, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-x"] = ngspipeline_sheet.cell_value(22, 7)
        if ngspipeline_sheet.cell_value(23, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-y"] = ngspipeline_sheet.cell_value(23, 7)
        if ngspipeline_sheet.cell_value(24, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["--zero-cap"] = ngspipeline_sheet.cell_value(24, 7)
        if ngspipeline_sheet.cell_value(25, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-m"] = ngspipeline_sheet.cell_value(25, 7)
        if ngspipeline_sheet.cell_value(26, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-M"] = ngspipeline_sheet.cell_value(26, 7)
        if ngspipeline_sheet.cell_value(27, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["--max-n"] = ngspipeline_sheet.cell_value(27, 7)
        if ngspipeline_sheet.cell_value(28, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["--discard-trimmed"] = ngspipeline_sheet.cell_value(28, 7)
        if ngspipeline_sheet.cell_value(29, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["--discard-untrimmed"] = ngspipeline_sheet.cell_value(29, 7)
        if ngspipeline_sheet.cell_value(30, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["--discard-casava"] = ngspipeline_sheet.cell_value(30, 7)
        if ngspipeline_sheet.cell_value(31, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-A"] = ngspipeline_sheet.cell_value(31, 7)
        if ngspipeline_sheet.cell_value(32, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-G"] = ngspipeline_sheet.cell_value(32, 7)
        if ngspipeline_sheet.cell_value(33, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-B"] = ngspipeline_sheet.cell_value(33, 7)
        if ngspipeline_sheet.cell_value(34, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-U"] = ngspipeline_sheet.cell_value(34, 7)
        if ngspipeline_sheet.cell_value(35, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["-p"] = ngspipeline_sheet.cell_value(35, 7)
        if ngspipeline_sheet.cell_value(36, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["--pair-adapters"] = ngspipeline_sheet.cell_value(36, 7)
        if ngspipeline_sheet.cell_value(37, 7) != "":
            self.conf['ngs_pipeline']['preprocessing']["cutadapt"]["--pair-filter"] = ngspipeline_sheet.cell_value(37, 7)
            
        if ngspipeline_sheet.cell_value(60, 1) ==True:
            self.conf['ngs_pipeline']['decontamination']['enable'] = True
        if ngspipeline_sheet.cell_value(61, 1) !="":
            self.conf['ngs_pipeline']['decontamination']['contaminant'] = ngspipeline_sheet.cell_value(61, 1)
            
        if ngspipeline_sheet.cell_value(62, 1) ==True:
            self.conf['ngs_pipeline']['assembly']['enable'] = True 
        if ngspipeline_sheet.cell_value(64, 1) ==True:
            self.conf['ngs_pipeline']['assembly']['megahit']['enable'] = True 
        if ngspipeline_sheet.cell_value(65, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["--min-count"] = ngspipeline_sheet.cell_value(65, 1)
        if ngspipeline_sheet.cell_value(66, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["--k-list"] = ngspipeline_sheet.cell_value(66, 1)
        if ngspipeline_sheet.cell_value(67, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["--no-mercy"] = ngspipeline_sheet.cell_value(67, 1)
        if ngspipeline_sheet.cell_value(68, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["--bubble-level"] = ngspipeline_sheet.cell_value(68, 1)
        if ngspipeline_sheet.cell_value(69, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["--merge-level"] = ngspipeline_sheet.cell_value(69, 1)
        if ngspipeline_sheet.cell_value(70, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["--prune-level"] = ngspipeline_sheet.cell_value(70, 1)
        if ngspipeline_sheet.cell_value(71, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["--prune-depth"] = ngspipeline_sheet.cell_value(71, 1)
        if ngspipeline_sheet.cell_value(72, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["--low-local-ratio"] = ngspipeline_sheet.cell_value(72, 1)
        if ngspipeline_sheet.cell_value(73, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["--max-tip-len"] = ngspipeline_sheet.cell_value(73, 1)
        if ngspipeline_sheet.cell_value(74, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["--no-local"] = ngspipeline_sheet.cell_value(74, 1)
        if ngspipeline_sheet.cell_value(75, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["--kmin-1pass"] = ngspipeline_sheet.cell_value(75, 1)
        if ngspipeline_sheet.cell_value(76, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["-m"] = ngspipeline_sheet.cell_value(76, 1)
        if ngspipeline_sheet.cell_value(77, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["--mem-flag"] = ngspipeline_sheet.cell_value(77, 1)
        if ngspipeline_sheet.cell_value(78, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["-t"] = ngspipeline_sheet.cell_value(78, 1)
        if ngspipeline_sheet.cell_value(79, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["--no-hw-accel"] = ngspipeline_sheet.cell_value(79, 1)
        if ngspipeline_sheet.cell_value(80, 1) != "":
            self.conf['ngs_pipeline']['assembly']["megahit"]["--min-contig-len"] = ngspipeline_sheet.cell_value(80, 1)
        
        if ngspipeline_sheet.cell_value(64, 3) == True:
            self.conf['ngs_pipeline']['assembly']["spades"]["enable"] = True
        if ngspipeline_sheet.cell_value(65, 3) != "":
            self.conf['ngs_pipeline']['assembly']["spades"]["--iontorrent"] = ngspipeline_sheet.cell_value(65, 3)
        if ngspipeline_sheet.cell_value(66, 3) != "":
            self.conf['ngs_pipeline']['assembly']["spades"]["--pacbio"] = ngspipeline_sheet.cell_value(66, 3)
        if ngspipeline_sheet.cell_value(67, 3) != "":
            self.conf['ngs_pipeline']['assembly']["spades"]["--nanopore"] = ngspipeline_sheet.cell_value(67, 3)
        if ngspipeline_sheet.cell_value(68, 3) != "":
            self.conf['ngs_pipeline']['assembly']["spades"]["-t"] = ngspipeline_sheet.cell_value(68, 3)
        if ngspipeline_sheet.cell_value(69, 3) != "":
            self.conf['ngs_pipeline']['assembly']["spades"]["-m"] = ngspipeline_sheet.cell_value(69, 3)
        if ngspipeline_sheet.cell_value(70, 3) != "":
            self.conf['ngs_pipeline']['assembly']["spades"]["-k"] = ngspipeline_sheet.cell_value(70, 3)
        if ngspipeline_sheet.cell_value(71, 3) != "":
            self.conf['ngs_pipeline']['assembly']["spades"]["--cov-cutoff"] = ngspipeline_sheet.cell_value(71, 3)
        if ngspipeline_sheet.cell_value(72, 3) != "":
            self.conf['ngs_pipeline']['assembly']["spades"]["--phred-offset"] = ngspipeline_sheet.cell_value(72, 3)
        if ngspipeline_sheet.cell_value(73, 3) == True:
            self.conf['ngs_pipeline']['assembly']["spades"]["--meta"] = True
        if ngspipeline_sheet.cell_value(64, 5) == True:
            self.conf['ngs_pipeline']['assembly']['idba-ud']["enable"] = True
        if ngspipeline_sheet.cell_value(65, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['-r'] = ngspipeline_sheet.cell_value(65, 5)
        if ngspipeline_sheet.cell_value(66, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--read_level_2'] = ngspipeline_sheet.cell_value(66, 5) 
        if ngspipeline_sheet.cell_value(67, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--read_level_3'] = ngspipeline_sheet.cell_value(67, 5) 
        if ngspipeline_sheet.cell_value(68, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--read_level_4'] = ngspipeline_sheet.cell_value(68, 5) 
        if ngspipeline_sheet.cell_value(69, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--read_level_5'] = ngspipeline_sheet.cell_value(69, 5) 
        if ngspipeline_sheet.cell_value(70, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['-l'] = ngspipeline_sheet.cell_value(70, 5) 
        if ngspipeline_sheet.cell_value(71, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--mink'] = str(int(ngspipeline_sheet.cell_value(71, 5)))
        if ngspipeline_sheet.cell_value(72, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--maxk'] = str(int(ngspipeline_sheet.cell_value(72, 5)))
        if ngspipeline_sheet.cell_value(73, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--step'] = str(int(ngspipeline_sheet.cell_value(73, 5))) 
        if ngspipeline_sheet.cell_value(74, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--prefix'] = str(int(ngspipeline_sheet.cell_value(74, 5))) 
        if ngspipeline_sheet.cell_value(75, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--min_count'] = str(int(ngspipeline_sheet.cell_value(75, 5))) 
        if ngspipeline_sheet.cell_value(76, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--min_support'] = str(int(ngspipeline_sheet.cell_value(76, 5))) 
        if ngspipeline_sheet.cell_value(77, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--num_threads'] = str(int(ngspipeline_sheet.cell_value(77, 5))) 
        if ngspipeline_sheet.cell_value(78, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--seed_kmer'] = str(int(ngspipeline_sheet.cell_value(78, 5))) 
        if ngspipeline_sheet.cell_value(79, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--min_contig'] = str(int(ngspipeline_sheet.cell_value(79, 5))) 
        if ngspipeline_sheet.cell_value(80, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--similar'] = ngspipeline_sheet.cell_value(80, 5) 
        if ngspipeline_sheet.cell_value(81, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--max_mismatch'] = str(int(ngspipeline_sheet.cell_value(81, 5))) 
        if ngspipeline_sheet.cell_value(82, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--min_pairs'] = str(int(ngspipeline_sheet.cell_value(82, 5))) 
        if ngspipeline_sheet.cell_value(83, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--no_coverage'] = True
        if ngspipeline_sheet.cell_value(84, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--no_correct'] = True 
        if ngspipeline_sheet.cell_value(85, 5) != '':
            self.conf['ngs_pipeline']['assembly']['idba-ud']['--pre_correction'] = True 
            
        if ngspipeline_sheet.cell_value(62, 7) == True:
            self.conf['ngs_pipeline']['Species_Annotation']['enable'] = True 
        if ngspipeline_sheet.cell_value(64, 7) == True:
            self.conf['ngs_pipeline']['Species_Annotation']['Kraken2']['enable'] = True 
        if ngspipeline_sheet.cell_value(65, 7) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['Kraken2']['--quick'] = ngspipeline_sheet.cell_value(65, 7) 
        if ngspipeline_sheet.cell_value(66, 7) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['Kraken2']['--minimum-hit-groups'] = str(int(ngspipeline_sheet.cell_value(66, 7)))
        if ngspipeline_sheet.cell_value(67, 7) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['Kraken2']['--confidence'] = ngspipeline_sheet.cell_value(67, 7)
        if ngspipeline_sheet.cell_value(68, 7) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['Kraken2']['--minimum-base-quality'] = str(int(ngspipeline_sheet.cell_value(68, 7)))
        if ngspipeline_sheet.cell_value(69, 7) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['Kraken2']['--gzip-compressed'] = ngspipeline_sheet.cell_value(69, 7)
        if ngspipeline_sheet.cell_value(70, 7) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['Kraken2']['--bzip2-compressed'] = ngspipeline_sheet.cell_value(70, 7)
        if ngspipeline_sheet.cell_value(71, 7) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['Kraken2']['--use-mpa-style'] = ngspipeline_sheet.cell_value(71, 7)
        if ngspipeline_sheet.cell_value(72, 7) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['Kraken2']['--use-names'] = ngspipeline_sheet.cell_value(72, 7)
        
        if ngspipeline_sheet.cell_value(64, 9) == True:
            self.conf['ngs_pipeline']['Species_Annotation']['MetaOthello']['enable'] = True 
        if ngspipeline_sheet.cell_value(65, 9) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaOthello']['kmer_length'] = str(int(ngspipeline_sheet.cell_value(65, 9))) 
        if ngspipeline_sheet.cell_value(66, 9) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaOthello']['db_kmer_length'] = str(int(ngspipeline_sheet.cell_value(66, 9))) 
        if ngspipeline_sheet.cell_value(67, 9) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaOthello']['path_to_bacterial_referenceSeqFastaFile'] = ngspipeline_sheet.cell_value(67, 9) 
        if ngspipeline_sheet.cell_value(68, 9) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaOthello']['bacterial_reference_seq_associated_taxonomy_info_file'] = ngspipeline_sheet.cell_value(68, 9) 
        
        if ngspipeline_sheet.cell_value(64, 11) == True:
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['enable'] = True 
        if ngspipeline_sheet.cell_value(65, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--input_type'] = ngspipeline_sheet.cell_value(65, 11) 
        if ngspipeline_sheet.cell_value(66, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--bt2_ps'] = ngspipeline_sheet.cell_value(66, 11) 
        if ngspipeline_sheet.cell_value(67, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--tax_lev'] = ngspipeline_sheet.cell_value(67, 11) 
        if ngspipeline_sheet.cell_value(68, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--min_cu_len'] = str(int(ngspipeline_sheet.cell_value(68, 11)))
        if ngspipeline_sheet.cell_value(69, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--min_alignment_len'] = str(int(ngspipeline_sheet.cell_value(69, 11)))
        if ngspipeline_sheet.cell_value(70, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--ignore_viruses'] = ngspipeline_sheet.cell_value(70, 11) 
        if ngspipeline_sheet.cell_value(71, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--ignore_eukaryotes'] = ngspipeline_sheet.cell_value(71, 11) 
        if ngspipeline_sheet.cell_value(72, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--ignore_bacteria'] = ngspipeline_sheet.cell_value(72, 11) 
        if ngspipeline_sheet.cell_value(73, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--ignore_archaea'] = ngspipeline_sheet.cell_value(73, 11) 
        if ngspipeline_sheet.cell_value(74, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--avoid_disqm'] = ngspipeline_sheet.cell_value(74, 11) 
        if ngspipeline_sheet.cell_value(75, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--no_map'] = ngspipeline_sheet.cell_value(75, 11) 
        if ngspipeline_sheet.cell_value(76, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--stat_q'] = ngspipeline_sheet.cell_value(76, 11) 
        if ngspipeline_sheet.cell_value(77, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--ignore_markers'] = ngspipeline_sheet.cell_value(77, 11) 
        if ngspipeline_sheet.cell_value(78, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--stat'] = ngspipeline_sheet.cell_value(78, 11) 
        if ngspipeline_sheet.cell_value(79, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['-t'] = ngspipeline_sheet.cell_value(79, 11) 
        if ngspipeline_sheet.cell_value(80, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--nreads'] = str(int(ngspipeline_sheet.cell_value(80, 11)))
        if ngspipeline_sheet.cell_value(81, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--pres_th'] = ngspipeline_sheet.cell_value(81, 11) 
        if ngspipeline_sheet.cell_value(82, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--clade'] = ngspipeline_sheet.cell_value(82, 11) 
        if ngspipeline_sheet.cell_value(83, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--min_ab'] = ngspipeline_sheet.cell_value(83, 11) 
        if ngspipeline_sheet.cell_value(84, 11) != '':
            self.conf['ngs_pipeline']['Species_Annotation']['MetaPhlAn2']['--read_min_len'] = str(int(ngspipeline_sheet.cell_value(84, 11)))
        
        if ngspipeline_sheet.cell_value(86, 1) == True:
            self.conf['ngs_pipeline']['gene_predition']['enable'] = True 
        if ngspipeline_sheet.cell_value(88, 1) == True:
            self.conf['ngs_pipeline']['gene_predition']['prodigal']['enable'] = True 
        if ngspipeline_sheet.cell_value(89, 1) != '':
            self.conf['ngs_pipeline']['gene_predition']['prodigal']['-c'] = ngspipeline_sheet.cell_value(89, 1) 
        if ngspipeline_sheet.cell_value(90, 1) != '':
            self.conf['ngs_pipeline']['gene_predition']['prodigal']['-m'] = str(int(ngspipeline_sheet.cell_value(90, 1)))
        if ngspipeline_sheet.cell_value(91, 1) == True:
            self.conf['ngs_pipeline']['gene_predition']['prodigal']['-n'] = True
        if ngspipeline_sheet.cell_value(92, 1) != '':
            self.conf['ngs_pipeline']['gene_predition']['prodigal']['-s'] = ngspipeline_sheet.cell_value(92, 1) 
        if ngspipeline_sheet.cell_value(93, 1) != '':
            self.conf['ngs_pipeline']['gene_predition']['prodigal']['-t'] = ngspipeline_sheet.cell_value(93, 1) 
        if ngspipeline_sheet.cell_value(94, 1) != '':
            self.conf['ngs_pipeline']['gene_predition']['prodigal']['-f'] = ngspipeline_sheet.cell_value(94, 1) 
        if ngspipeline_sheet.cell_value(95, 1) != '':
            self.conf['ngs_pipeline']['gene_predition']['prodigal']['-g'] = str(int(ngspipeline_sheet.cell_value(95, 1)))
        if ngspipeline_sheet.cell_value(96, 1) != '':
            self.conf['ngs_pipeline']['gene_predition']['prodigal']['-p'] = ngspipeline_sheet.cell_value(96, 1) 
                
        if ngspipeline_sheet.cell_value(88, 3) == True:
            self.conf['ngs_pipeline']['gene_predition']['metagenemark']['enable'] = True 
        if ngspipeline_sheet.cell_value(89, 3) != '':
            self.conf['ngs_pipeline']['gene_predition']['metagenemark']['-f'] = ngspipeline_sheet.cell_value(89, 3) 
        if ngspipeline_sheet.cell_value(90, 3) != '':
            self.conf['ngs_pipeline']['gene_predition']['metagenemark']['-K'] = ngspipeline_sheet.cell_value(90, 3) 
        if ngspipeline_sheet.cell_value(91, 3) != '':
            self.conf['ngs_pipeline']['gene_predition']['metagenemark']['-r'] = ngspipeline_sheet.cell_value(91, 3) 
        if ngspipeline_sheet.cell_value(92, 3) != '':
            self.conf['ngs_pipeline']['gene_predition']['metagenemark']['-c'] = ngspipeline_sheet.cell_value(92, 3) 
        if ngspipeline_sheet.cell_value(93, 3) != '':
            self.conf['ngs_pipeline']['gene_predition']['metagenemark']['-s'] = ngspipeline_sheet.cell_value(93, 3) 
        if ngspipeline_sheet.cell_value(94, 3) != '':
            self.conf['ngs_pipeline']['gene_predition']['metagenemark']['-p'] = str(int(ngspipeline_sheet.cell_value(94, 3)))
        if ngspipeline_sheet.cell_value(95, 3) != '':
            self.conf['ngs_pipeline']['gene_predition']['metagenemark']['-e'] = ngspipeline_sheet.cell_value(95, 3) 
        if ngspipeline_sheet.cell_value(96, 3) != '':
            self.conf['ngs_pipeline']['gene_predition']['metagenemark']['-g'] = str(int(ngspipeline_sheet.cell_value(96, 3)))
        
        if ngspipeline_sheet.cell_value(97, 1) == True:
            self.conf['ngs_pipeline']['functional_annotation']['enable'] = True 
        if ngspipeline_sheet.cell_value(99, 1) == True:
            self.conf['ngs_pipeline']['functional_annotation']['emapper.py']['enable'] = True 
        if ngspipeline_sheet.cell_value(100, 1) != '':
            self.conf['ngs_pipeline']['functional_annotation']['emapper.py']['--matrix'] = ngspipeline_sheet.cell_value(100, 1) 
        if ngspipeline_sheet.cell_value(101, 1) != '':
            self.conf['ngs_pipeline']['functional_annotation']['emapper.py']['--gapopen'] = str(int(ngspipeline_sheet.cell_value(101, 1)))
        if ngspipeline_sheet.cell_value(102, 1) != '':
            self.conf['ngs_pipeline']['functional_annotation']['emapper.py']['--gapextend'] = str(int(ngspipeline_sheet.cell_value(102, 1)))
        if ngspipeline_sheet.cell_value(103, 1) != '':
            self.conf['ngs_pipeline']['functional_annotation']['emapper.py']['--query-cover'] = ngspipeline_sheet.cell_value(103, 1) 
        if ngspipeline_sheet.cell_value(104, 1) != '':
            self.conf['ngs_pipeline']['functional_annotation']['emapper.py']['--subject-cover'] = ngspipeline_sheet.cell_value(104, 1) 
        if ngspipeline_sheet.cell_value(105, 1) != '':
            self.conf['ngs_pipeline']['functional_annotation']['emapper.py']['--seed_ortholog_evalue'] = ngspipeline_sheet.cell_value(105, 1) 
        if ngspipeline_sheet.cell_value(106, 1) != '':
            self.conf['ngs_pipeline']['functional_annotation']['emapper.py']['--seed_ortholog_score'] = ngspipeline_sheet.cell_value(106, 1) 
        if ngspipeline_sheet.cell_value(107, 1) != '':
            self.conf['ngs_pipeline']['functional_annotation']['emapper.py']['--target_taxa'] = ngspipeline_sheet.cell_value(107, 1) 
        if ngspipeline_sheet.cell_value(108, 1) != '':
            self.conf['ngs_pipeline']['functional_annotation']['emapper.py']['--predict_output_format'] = ngspipeline_sheet.cell_value(108, 1) 
        if ngspipeline_sheet.cell_value(109, 1) != '':
            self.conf['ngs_pipeline']['functional_annotation']['emapper.py']['--cpu'] = ngspipeline_sheet.cell_value(109, 1) 
        if ngspipeline_sheet.cell_value(99, 3) == True:
            self.conf['ngs_pipeline']['functional_annotation']['PHI_Annotation']['enable'] = True 
        if ngspipeline_sheet.cell_value(100, 3) != '':
            self.conf['ngs_pipeline']['functional_annotation']['PHI_Annotation']['plot_for_top_k'] = ngspipeline_sheet.cell_value(100, 3)
        if ngspipeline_sheet.cell_value(99, 5) == True:
            self.conf['ngs_pipeline']['functional_annotation']['VFDB_Annotation']['enable'] = True 
        if ngspipeline_sheet.cell_value(100, 5) != '':
            self.conf['ngs_pipeline']['functional_annotation']['VFDB_Annotation']['plot_for_top_k'] = ngspipeline_sheet.cell_value(100, 5)
        if ngspipeline_sheet.cell_value(99, 7) == True:
            self.conf['ngs_pipeline']['functional_annotation']['CARD_Annotation']['enable'] = True 
        if ngspipeline_sheet.cell_value(100, 7) != '':
            self.conf['ngs_pipeline']['functional_annotation']['CARD_Annotation']['plot_for_top_k'] = ngspipeline_sheet.cell_value(100, 7)
        if ngspipeline_sheet.cell_value(99, 9) == True:
            self.conf['ngs_pipeline']['functional_annotation']['TCDB_Annotation']['enable'] = True
        if ngspipeline_sheet.cell_value(100, 9) != '':
            self.conf['ngs_pipeline']['functional_annotation']['TCDB_Annotation']['plot_for_top_k'] = ngspipeline_sheet.cell_value(100, 9)
        if ngspipeline_sheet.cell_value(99, 11) == True:
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['enable'] = True 
        if ngspipeline_sheet.cell_value(100, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-evalue'] = ngspipeline_sheet.cell_value(100, 11) 
        if ngspipeline_sheet.cell_value(101, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-word_size'] = str(int(ngspipeline_sheet.cell_value(101, 11)))
        if ngspipeline_sheet.cell_value(102, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-gapopen'] = str(int(ngspipeline_sheet.cell_value(102, 11)))
        if ngspipeline_sheet.cell_value(103, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-gapextend'] = str(int(ngspipeline_sheet.cell_value(103, 11)))
        if ngspipeline_sheet.cell_value(104, 11) != '':
            i = ngspipeline_sheet.cell_value(104, 11)
            if isinstance(i,float):
                i = int(i)
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-comp_based_stats'] = i
        if ngspipeline_sheet.cell_value(105, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-seg'] = ngspipeline_sheet.cell_value(105, 11) 
        if ngspipeline_sheet.cell_value(106, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-qcov_hsp_perc'] = ngspipeline_sheet.cell_value(106, 11) 
        if ngspipeline_sheet.cell_value(107, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-max_hsps'] = str(int(ngspipeline_sheet.cell_value(107, 11)))
        if ngspipeline_sheet.cell_value(108, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-culling_limit'] = str(int(ngspipeline_sheet.cell_value(108, 11)))
        if ngspipeline_sheet.cell_value(109, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-best_hit_overhang'] = ngspipeline_sheet.cell_value(109, 11) 
        if ngspipeline_sheet.cell_value(110, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-best_hit_score_edge'] = ngspipeline_sheet.cell_value(110, 11) 
        if ngspipeline_sheet.cell_value(111, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-max_target_seqs'] = str(int(ngspipeline_sheet.cell_value(111, 11)))
        if ngspipeline_sheet.cell_value(112, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-xdrop_ungap'] = ngspipeline_sheet.cell_value(112, 11) 
        if ngspipeline_sheet.cell_value(113, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-xdrop_gap'] = ngspipeline_sheet.cell_value(113, 11) 
        if ngspipeline_sheet.cell_value(114, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-xdrop_gap_final'] = ngspipeline_sheet.cell_value(114, 11) 
        if ngspipeline_sheet.cell_value(115, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-window_size'] = str(int(ngspipeline_sheet.cell_value(115, 11)))
        if ngspipeline_sheet.cell_value(116, 11) != '':
            self.conf['ngs_pipeline']['functional_annotation']['blastp']['-ungapped'] = ngspipeline_sheet.cell_value(116, 11) 
        
        if ngspipeline_sheet.cell_value(99, 13) == True:
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['enable'] = True 
        if ngspipeline_sheet.cell_value(100, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--max-target-seqs'] = str(int(ngspipeline_sheet.cell_value(100, 13)))
        if ngspipeline_sheet.cell_value(101, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--top'] = ngspipeline_sheet.cell_value(101, 13) 
        if ngspipeline_sheet.cell_value(102, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--range-culling'] = ngspipeline_sheet.cell_value(102, 13) 
        if ngspipeline_sheet.cell_value(103, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--evalue'] = ngspipeline_sheet.cell_value(103, 13) 
        if ngspipeline_sheet.cell_value(104, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--min-score'] = ngspipeline_sheet.cell_value(104, 13) 
        if ngspipeline_sheet.cell_value(105, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--id'] = ngspipeline_sheet.cell_value(105, 13) 
        if ngspipeline_sheet.cell_value(106, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--query-cover'] = ngspipeline_sheet.cell_value(106, 13) 
        if ngspipeline_sheet.cell_value(107, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--subject-cover'] = ngspipeline_sheet.cell_value(107, 13) 
        if ngspipeline_sheet.cell_value(108, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--sensitive'] = ngspipeline_sheet.cell_value(108, 13) 
        if ngspipeline_sheet.cell_value(109, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--more-sensitive'] = ngspipeline_sheet.cell_value(109, 13) 
        if ngspipeline_sheet.cell_value(110, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--block-size'] = ngspipeline_sheet.cell_value(110, 13) 
        if ngspipeline_sheet.cell_value(111, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--index-chunks'] = str(int(ngspipeline_sheet.cell_value(111, 13)))
        if ngspipeline_sheet.cell_value(112, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--gapopen'] = str(int(ngspipeline_sheet.cell_value(112, 13)))
        if ngspipeline_sheet.cell_value(113, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--gapextend'] = str(int(ngspipeline_sheet.cell_value(113, 13)))
        if ngspipeline_sheet.cell_value(114, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--matrix'] = ngspipeline_sheet.cell_value(114, 13) 
        if ngspipeline_sheet.cell_value(115, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--comp-based-stats'] = str(int(ngspipeline_sheet.cell_value(115, 13)))
        if ngspipeline_sheet.cell_value(116, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--masking'] = str(int(ngspipeline_sheet.cell_value(116, 13)))
        if ngspipeline_sheet.cell_value(117, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--no-self-hits'] = ngspipeline_sheet.cell_value(117, 13) 
        if ngspipeline_sheet.cell_value(118, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--salltitles'] = ngspipeline_sheet.cell_value(118, 13) 
        if ngspipeline_sheet.cell_value(119, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--sallseqid'] = ngspipeline_sheet.cell_value(119, 13) 
        if ngspipeline_sheet.cell_value(120, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--algo'] = str(int(ngspipeline_sheet.cell_value(120, 13)))
        if ngspipeline_sheet.cell_value(121, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--bin'] = str(int(ngspipeline_sheet.cell_value(121, 13)))
        if ngspipeline_sheet.cell_value(122, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--min-orf'] = str(int(ngspipeline_sheet.cell_value(122, 13)))
        if ngspipeline_sheet.cell_value(123, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--freq-sd'] = str(int(ngspipeline_sheet.cell_value(123, 13)))
        if ngspipeline_sheet.cell_value(124, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--id2'] = str(int(ngspipeline_sheet.cell_value(124, 13)))
        if ngspipeline_sheet.cell_value(125, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--window'] = str(int(ngspipeline_sheet.cell_value(125, 13)))
        if ngspipeline_sheet.cell_value(126, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--xdrop'] = ngspipeline_sheet.cell_value(126, 13) 
        if ngspipeline_sheet.cell_value(127, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--ungapped-score'] = ngspipeline_sheet.cell_value(127, 13) 
        if ngspipeline_sheet.cell_value(128, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--band'] = ngspipeline_sheet.cell_value(128, 13) 
        if ngspipeline_sheet.cell_value(129, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--shapes'] = str(int(ngspipeline_sheet.cell_value(129, 13)))
        if ngspipeline_sheet.cell_value(130, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--shape-mask'] = ngspipeline_sheet.cell_value(130, 13) 
        if ngspipeline_sheet.cell_value(131, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--culling-overlap'] = ngspipeline_sheet.cell_value(131, 13) 
        if ngspipeline_sheet.cell_value(132, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--range-cover'] = ngspipeline_sheet.cell_value(132, 13) 
        if ngspipeline_sheet.cell_value(133, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--no-auto-append'] = ngspipeline_sheet.cell_value(133, 13) 
        if ngspipeline_sheet.cell_value(134, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--stop-match-score'] = ngspipeline_sheet.cell_value(134, 13) 
        if ngspipeline_sheet.cell_value(135, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--tantan-minMaskProb'] = ngspipeline_sheet.cell_value(135, 13) 
        if ngspipeline_sheet.cell_value(136, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--daa'] = ngspipeline_sheet.cell_value(136, 13) 
        if ngspipeline_sheet.cell_value(137, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--forwardonly'] = ngspipeline_sheet.cell_value(137, 13) 
        if ngspipeline_sheet.cell_value(138, 13) != '':
            self.conf['ngs_pipeline']['functional_annotation']['diamond']['--seq'] = str(int(ngspipeline_sheet.cell_value(138, 13)))
       
    def read_tgspipeline_configuration(self):
        self.conf['tgs_pipeline']['enable'] = True 
        tgspipeline_sheet = xlrd.open_workbook(self.conf_file_path).sheet_by_name('tgs_analysis_setting') 
        if tgspipeline_sheet.cell_value(3, 1) == True:
            self.conf['tgs_pipeline']['tgs_quality_control']['enable'] = True
        if tgspipeline_sheet.cell_value(5, 1) == True:
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['enable'] = True 
        if tgspipeline_sheet.cell_value(6, 1) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--maxlength'] = str(int(tgspipeline_sheet.cell_value(6, 1)))
        if tgspipeline_sheet.cell_value(7, 1) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--minlength'] = str(int(tgspipeline_sheet.cell_value(7, 1)))
        if tgspipeline_sheet.cell_value(8, 1) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--drop_outliers'] = tgspipeline_sheet.cell_value(8, 1) 
        if tgspipeline_sheet.cell_value(9, 1) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--loglength'] = tgspipeline_sheet.cell_value(9, 1) 
        if tgspipeline_sheet.cell_value(10, 1) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--barcoded'] = tgspipeline_sheet.cell_value(10, 1) 
        if tgspipeline_sheet.cell_value(11, 1) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--percentqual'] = tgspipeline_sheet.cell_value(11, 1) 
        if tgspipeline_sheet.cell_value(12, 1) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--downsample'] = str(int(tgspipeline_sheet.cell_value(12, 1)))
        if tgspipeline_sheet.cell_value(13, 1) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--minqual'] = str(int(tgspipeline_sheet.cell_value(13, 1)))
        if tgspipeline_sheet.cell_value(14, 1) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--readtype'] = tgspipeline_sheet.cell_value(14, 1) 
        if tgspipeline_sheet.cell_value(15, 1) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--color'] = tgspipeline_sheet.cell_value(15, 1) 
        if tgspipeline_sheet.cell_value(16, 1) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--format'] = tgspipeline_sheet.cell_value(16, 1) 
        if tgspipeline_sheet.cell_value(18, 2) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--plots']['dot'] = tgspipeline_sheet.cell_value(18, 2) 
        if tgspipeline_sheet.cell_value(19, 2) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--plots']['kde'] = tgspipeline_sheet.cell_value(19, 2) 
        if tgspipeline_sheet.cell_value(20, 2) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--plots']['hex'] = tgspipeline_sheet.cell_value(20, 2) 
        if tgspipeline_sheet.cell_value(21, 2) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--plots']['pauvre'] = tgspipeline_sheet.cell_value(21, 2) 
        if tgspipeline_sheet.cell_value(22, 1) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--no-N50'] = tgspipeline_sheet.cell_value(22, 1) 
        if tgspipeline_sheet.cell_value(23, 1) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--N50'] = tgspipeline_sheet.cell_value(23, 1) 
        if tgspipeline_sheet.cell_value(24, 1) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoPlot']['--title'] = tgspipeline_sheet.cell_value(24, 1) 
        
        if tgspipeline_sheet.cell_value(5, 4) == True:
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoFilt']['enable'] = True 
        if tgspipeline_sheet.cell_value(6, 4) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoFilt']['--maxlength'] = str(int(tgspipeline_sheet.cell_value(6, 4)))
        if tgspipeline_sheet.cell_value(7, 4) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoFilt']['--length'] = str(int(tgspipeline_sheet.cell_value(7, 4)))
        if tgspipeline_sheet.cell_value(8, 4) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoFilt']['--quality'] = str(int(tgspipeline_sheet.cell_value(8, 4)))
        if tgspipeline_sheet.cell_value(9, 4) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoFilt']['--minGC'] = tgspipeline_sheet.cell_value(9, 4) 
        if tgspipeline_sheet.cell_value(10, 4) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoFilt']['--maxGC'] = tgspipeline_sheet.cell_value(10, 4) 
        if tgspipeline_sheet.cell_value(11, 4) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['NanoFilt']['--readtype'] = tgspipeline_sheet.cell_value(11, 4) 
        
        if tgspipeline_sheet.cell_value(5, 6) == True:
            self.conf['tgs_pipeline']['tgs_quality_control']['Filtlong']['enable'] = True 
        if tgspipeline_sheet.cell_value(6, 6) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Filtlong']['--target_bases'] = tgspipeline_sheet.cell_value(6, 6) 
        if tgspipeline_sheet.cell_value(7, 6) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Filtlong']['--keep_percent'] = tgspipeline_sheet.cell_value(7, 6) 
        if tgspipeline_sheet.cell_value(8, 6) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Filtlong']['--min_length'] = str(int(tgspipeline_sheet.cell_value(8, 6)))
        if tgspipeline_sheet.cell_value(9, 6) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Filtlong']['--min_mean_q'] = tgspipeline_sheet.cell_value(9, 6)
        if tgspipeline_sheet.cell_value(10, 6) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Filtlong']['--min_window_q'] = tgspipeline_sheet.cell_value(10, 6) 
        if tgspipeline_sheet.cell_value(11, 6) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Filtlong']['--length_weight'] = tgspipeline_sheet.cell_value(11, 6) 
        if tgspipeline_sheet.cell_value(12, 6) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Filtlong']['--mean_q_weight'] = tgspipeline_sheet.cell_value(12, 6) 
        if tgspipeline_sheet.cell_value(13, 6) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Filtlong']['--window_q_weight'] = tgspipeline_sheet.cell_value(13, 6) 
        if tgspipeline_sheet.cell_value(14, 6) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Filtlong']['--trim'] = tgspipeline_sheet.cell_value(14, 6) 
        if tgspipeline_sheet.cell_value(15, 6) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Filtlong']['--split'] = tgspipeline_sheet.cell_value(15, 6) 
        if tgspipeline_sheet.cell_value(16, 6) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Filtlong']['--window_size'] = str(int(tgspipeline_sheet.cell_value(16, 6)))
        if tgspipeline_sheet.cell_value(5, 8) == True:
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['enable'] = True
        if tgspipeline_sheet.cell_value(6, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--barcode_dir'] = tgspipeline_sheet.cell_value(6, 8)
        if tgspipeline_sheet.cell_value(7, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--barcode_threshold'] = tgspipeline_sheet.cell_value(7, 8)
        if tgspipeline_sheet.cell_value(8, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--barcode_diff'] = tgspipeline_sheet.cell_value(8, 8)
        if tgspipeline_sheet.cell_value(9, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--require_two_barcodes'] = tgspipeline_sheet.cell_value(9, 8)
        if tgspipeline_sheet.cell_value(10, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--untrimmed'] = tgspipeline_sheet.cell_value(10, 8)
        if tgspipeline_sheet.cell_value(11, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--discard_unassigned'] = tgspipeline_sheet.cell_value(11, 8)
        if tgspipeline_sheet.cell_value(12, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--adapter_threshold'] = tgspipeline_sheet.cell_value(12, 8)
        if tgspipeline_sheet.cell_value(13, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--check_reads'] = tgspipeline_sheet.cell_value(13, 8)
        if tgspipeline_sheet.cell_value(14, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--scoring_scheme'] = tgspipeline_sheet.cell_value(14, 8)
        if tgspipeline_sheet.cell_value(15, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--end_size'] = tgspipeline_sheet.cell_value(15, 8)
        if tgspipeline_sheet.cell_value(16, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--min_trim_size'] = tgspipeline_sheet.cell_value(16, 8)
        if tgspipeline_sheet.cell_value(17, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--extra_end_trim'] = tgspipeline_sheet.cell_value(17, 8)
        if tgspipeline_sheet.cell_value(18, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--end_threshold'] = tgspipeline_sheet.cell_value(18, 8)
        if tgspipeline_sheet.cell_value(19, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--no_split'] = tgspipeline_sheet.cell_value(19, 8)
        if tgspipeline_sheet.cell_value(20, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--discard_middle'] = tgspipeline_sheet.cell_value(20, 8)
        if tgspipeline_sheet.cell_value(21, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--middle_threshold'] = tgspipeline_sheet.cell_value(21, 8)
        if tgspipeline_sheet.cell_value(22, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--extra_middle_trim_good_side'] = tgspipeline_sheet.cell_value(22, 8)
        if tgspipeline_sheet.cell_value(23, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--extra_middle_trim_bad_side'] = tgspipeline_sheet.cell_value(23, 8)
        if tgspipeline_sheet.cell_value(24, 8) != '':
            self.conf['tgs_pipeline']['tgs_quality_control']['Porechop']['--min_split_read_size'] = tgspipeline_sheet.cell_value(24, 8)
        
        
        
        if tgspipeline_sheet.cell_value(26, 1) == True:
            self.conf['tgs_pipeline']['assembly']['enable'] = True 
        if tgspipeline_sheet.cell_value(28, 1) == True:
            self.conf['tgs_pipeline']['assembly']['canu']['enable'] = True 
        if tgspipeline_sheet.cell_value(29, 1) != '':
            self.conf['tgs_pipeline']['assembly']['canu']['genomeSize'] = tgspipeline_sheet.cell_value(29, 1) 
        if tgspipeline_sheet.cell_value(30, 1) != '':
            self.conf['tgs_pipeline']['assembly']['canu']['-pacbio-raw'] = tgspipeline_sheet.cell_value(30, 1) 
        if tgspipeline_sheet.cell_value(31, 1) != '':
            self.conf['tgs_pipeline']['assembly']['canu']['-pacbio-corrected'] = tgspipeline_sheet.cell_value(31, 1) 
        if tgspipeline_sheet.cell_value(32, 1) != '':
            self.conf['tgs_pipeline']['assembly']['canu']['-nanopore-raw'] = tgspipeline_sheet.cell_value(32, 1) 
        if tgspipeline_sheet.cell_value(33, 1) != '':
            self.conf['tgs_pipeline']['assembly']['canu']['-nanopore-corrected'] = tgspipeline_sheet.cell_value(33, 1) 
        if tgspipeline_sheet.cell_value(34, 1) != '':
            self.conf['tgs_pipeline']['assembly']['canu']['-p'] = tgspipeline_sheet.cell_value(34, 1) 
        if tgspipeline_sheet.cell_value(35, 1) != '':
            self.conf['tgs_pipeline']['assembly']['canu']['rawErrorRate'] = tgspipeline_sheet.cell_value(35, 1) 
        if tgspipeline_sheet.cell_value(36, 1) != '':
            self.conf['tgs_pipeline']['assembly']['canu']['correctedErrorRate'] = tgspipeline_sheet.cell_value(36, 1) 
        if tgspipeline_sheet.cell_value(37, 1) != '':
            self.conf['tgs_pipeline']['assembly']['canu']['minReadLength'] = str(int(tgspipeline_sheet.cell_value(37, 1)))
        if tgspipeline_sheet.cell_value(38, 1) != '':
            self.conf['tgs_pipeline']['assembly']['canu']['minOverlapLength'] = str(int(tgspipeline_sheet.cell_value(38, 1)))
        
        if tgspipeline_sheet.cell_value(28, 3) == True:
            self.conf['tgs_pipeline']['assembly']['Flye']['enable'] = True 
        if tgspipeline_sheet.cell_value(29, 3) != '':
            self.conf['tgs_pipeline']['assembly']['Flye']['--input_type'] = tgspipeline_sheet.cell_value(29, 3) 
            print(self.conf['tgs_pipeline']['assembly']['Flye']['--input_type'])
        if tgspipeline_sheet.cell_value(30, 3) != '':
            self.conf['tgs_pipeline']['assembly']['Flye']['--genome-size'] = tgspipeline_sheet.cell_value(30, 3) 
        if tgspipeline_sheet.cell_value(31, 3) != '':
            self.conf['tgs_pipeline']['assembly']['Flye']['--iterations'] = str(int(tgspipeline_sheet.cell_value(31, 3)))
        if tgspipeline_sheet.cell_value(32, 3) != '':
            self.conf['tgs_pipeline']['assembly']['Flye']['--min-overlap'] = str(int(tgspipeline_sheet.cell_value(32, 3)))
        if tgspipeline_sheet.cell_value(33, 3) != '':
            self.conf['tgs_pipeline']['assembly']['Flye']['--asm-coverage'] = str(int(tgspipeline_sheet.cell_value(33, 3)))
        if tgspipeline_sheet.cell_value(34, 3) != '':
            self.conf['tgs_pipeline']['assembly']['Flye']['--hifi-error'] = tgspipeline_sheet.cell_value(34, 3) 
        if tgspipeline_sheet.cell_value(35, 3) != '':
            self.conf['tgs_pipeline']['assembly']['Flye']['--meta'] = tgspipeline_sheet.cell_value(35, 3) 
        if tgspipeline_sheet.cell_value(36, 3) != '':
            self.conf['tgs_pipeline']['assembly']['Flye']['--plasmids'] = tgspipeline_sheet.cell_value(36, 3) 
        if tgspipeline_sheet.cell_value(37, 3) != '':
            self.conf['tgs_pipeline']['assembly']['Flye']['--trestle'] = tgspipeline_sheet.cell_value(37, 3) 
        if tgspipeline_sheet.cell_value(38, 3) != '':
            self.conf['tgs_pipeline']['assembly']['Flye']['--polish-target'] = tgspipeline_sheet.cell_value(38, 3) 
        if tgspipeline_sheet.cell_value(39, 3) != '':
            self.conf['tgs_pipeline']['assembly']['Flye']['--keep-haplotypes'] = tgspipeline_sheet.cell_value(39, 3) 
      
        if tgspipeline_sheet.cell_value(28, 7) ==True:
            self.conf['tgs_pipeline']['assembly']['SMARTdenovo']['enable'] = True 
        if tgspipeline_sheet.cell_value(29, 7) != '':
            self.conf['tgs_pipeline']['assembly']['SMARTdenovo']['-p'] = tgspipeline_sheet.cell_value(29, 7) 
        if tgspipeline_sheet.cell_value(30, 7) != '':
            self.conf['tgs_pipeline']['assembly']['SMARTdenovo']['-e'] = tgspipeline_sheet.cell_value(30, 7) 
        if tgspipeline_sheet.cell_value(31, 7) != '':
            self.conf['tgs_pipeline']['assembly']['SMARTdenovo']['-k'] = str(int(tgspipeline_sheet.cell_value(31, 7)))
        if tgspipeline_sheet.cell_value(32, 7) != '':
            self.conf['tgs_pipeline']['assembly']['SMARTdenovo']['-J'] = str(int(tgspipeline_sheet.cell_value(32, 7)))
        if tgspipeline_sheet.cell_value(33, 7) != '':
            self.conf['tgs_pipeline']['assembly']['SMARTdenovo']['-c'] = str(int(tgspipeline_sheet.cell_value(33, 7)))
        
    
        if tgspipeline_sheet.cell_value(47, 1) ==True:
            self.conf['tgs_pipeline']['Polish']['enable'] = True 
        if tgspipeline_sheet.cell_value(49, 1) ==True:
            self.conf['tgs_pipeline']['Polish']['Racon']['enable'] = True 
        if tgspipeline_sheet.cell_value(50, 1) != '':
            self.conf['tgs_pipeline']['Polish']['Racon']['-w'] = str(int(tgspipeline_sheet.cell_value(50, 1)))
        if tgspipeline_sheet.cell_value(51, 1) != '':
            self.conf['tgs_pipeline']['Polish']['Racon']['-q'] = tgspipeline_sheet.cell_value(51, 1) 
        if tgspipeline_sheet.cell_value(52, 1) != '':
            self.conf['tgs_pipeline']['Polish']['Racon']['-e'] = tgspipeline_sheet.cell_value(52, 1) 
        if tgspipeline_sheet.cell_value(53, 1) != '':
            self.conf['tgs_pipeline']['Polish']['Racon']['-m'] = str(int(tgspipeline_sheet.cell_value(53, 1)))
        if tgspipeline_sheet.cell_value(54, 1) != '':
            self.conf['tgs_pipeline']['Polish']['Racon']['-x'] = str(int(tgspipeline_sheet.cell_value(54, 1)))
        if tgspipeline_sheet.cell_value(55, 1) != '':
            self.conf['tgs_pipeline']['Polish']['Racon']['-g'] = str(int(tgspipeline_sheet.cell_value(55, 1)))
        if tgspipeline_sheet.cell_value(56, 1) != '':
            self.conf['tgs_pipeline']['Polish']['Racon']['-u'] = tgspipeline_sheet.cell_value(56, 1) 
        if tgspipeline_sheet.cell_value(57, 1) != '':
            self.conf['tgs_pipeline']['Polish']['Racon']['--no-trimming'] = tgspipeline_sheet.cell_value(57, 1) 
        
        if tgspipeline_sheet.cell_value(49, 3) ==True:
            self.conf['tgs_pipeline']['Polish']['Pilon']['enable'] = True 
        if tgspipeline_sheet.cell_value(50, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--output'] = tgspipeline_sheet.cell_value(50, 3) 
        if tgspipeline_sheet.cell_value(51, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--changes'] = tgspipeline_sheet.cell_value(51, 3) 
        if tgspipeline_sheet.cell_value(52, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--vcf'] = tgspipeline_sheet.cell_value(52, 3) 
        if tgspipeline_sheet.cell_value(53, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--vcfqe'] = tgspipeline_sheet.cell_value(53, 3) 
        if tgspipeline_sheet.cell_value(54, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--tracks'] = tgspipeline_sheet.cell_value(54, 3) 
        if tgspipeline_sheet.cell_value(55, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--variant'] = tgspipeline_sheet.cell_value(55, 3) 
        if tgspipeline_sheet.cell_value(56, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--chunksize'] = tgspipeline_sheet.cell_value(56, 3) 
        if tgspipeline_sheet.cell_value(57, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--diploid'] = tgspipeline_sheet.cell_value(57, 3) 
        if tgspipeline_sheet.cell_value(59, 4) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--fix']['snps'] = tgspipeline_sheet.cell_value(59, 4) 
        if tgspipeline_sheet.cell_value(60, 4) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--fix']['indels'] = tgspipeline_sheet.cell_value(60, 4) 
        if tgspipeline_sheet.cell_value(61, 4) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--fix']['gaps'] = tgspipeline_sheet.cell_value(61, 4) 
        if tgspipeline_sheet.cell_value(62, 4) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--fix']['local'] = tgspipeline_sheet.cell_value(62, 4) 
        if tgspipeline_sheet.cell_value(63, 4) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--fix']['all'] = tgspipeline_sheet.cell_value(63, 4) 
        if tgspipeline_sheet.cell_value(64, 4) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--fix']['bases'] = tgspipeline_sheet.cell_value(64, 4) 
        if tgspipeline_sheet.cell_value(65, 4) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--fix']['none'] = tgspipeline_sheet.cell_value(65, 4) 
        if tgspipeline_sheet.cell_value(66, 4) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--fix']['amb'] = tgspipeline_sheet.cell_value(66, 4) 
        if tgspipeline_sheet.cell_value(67, 4) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--fix']['breaks'] = tgspipeline_sheet.cell_value(67, 4) 
        if tgspipeline_sheet.cell_value(68, 4) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--fix']['circles'] = tgspipeline_sheet.cell_value(68, 4) 
        if tgspipeline_sheet.cell_value(69, 4) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--fix']['novel'] = tgspipeline_sheet.cell_value(69, 4) 
        if tgspipeline_sheet.cell_value(70, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--dumpreads'] = tgspipeline_sheet.cell_value(70, 3) 
        if tgspipeline_sheet.cell_value(71, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--duplicates'] = tgspipeline_sheet.cell_value(71, 3) 
        if tgspipeline_sheet.cell_value(72, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--iupac'] = tgspipeline_sheet.cell_value(72, 3) 
        if tgspipeline_sheet.cell_value(73, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--nonpf'] = tgspipeline_sheet.cell_value(73, 3) 
        if tgspipeline_sheet.cell_value(74, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--targets'] = tgspipeline_sheet.cell_value(74, 3) 
        if tgspipeline_sheet.cell_value(75, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--defaultqual'] = str(int(tgspipeline_sheet.cell_value(75, 3)))
        if tgspipeline_sheet.cell_value(76, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--flank'] = str(int(tgspipeline_sheet.cell_value(76, 3)))
        if tgspipeline_sheet.cell_value(77, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--gapmargin'] = str(int(tgspipeline_sheet.cell_value(77, 3)))
        if tgspipeline_sheet.cell_value(78, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--K'] = str(int(tgspipeline_sheet.cell_value(78, 3)))
        if tgspipeline_sheet.cell_value(79, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--mindepth'] = tgspipeline_sheet.cell_value(79, 3) 
        if tgspipeline_sheet.cell_value(80, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--mingap'] = str(int(tgspipeline_sheet.cell_value(80, 3)))
        if tgspipeline_sheet.cell_value(81, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--minmq'] = str(int(tgspipeline_sheet.cell_value(81, 3)))
        if tgspipeline_sheet.cell_value(82, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--minqual'] = str(int(tgspipeline_sheet.cell_value(82, 3)))
        if tgspipeline_sheet.cell_value(83, 3) != '':
            self.conf['tgs_pipeline']['Polish']['Pilon']['--nostrays'] = tgspipeline_sheet.cell_value(83, 3) 
        
        if tgspipeline_sheet.cell_value(85, 1) ==True:
            self.conf['tgs_pipeline']['decontamination']['enable'] = True
        if tgspipeline_sheet.cell_value(86, 1) !="":
            self.conf['tgs_pipeline']['decontamination']['contaminant'] = tgspipeline_sheet.cell_value(86, 1)
        if tgspipeline_sheet.cell_value(86, 3) !="":
            self.conf['tgs_pipeline']['decontamination']['input_type'] = tgspipeline_sheet.cell_value(86, 3)
        
        if tgspipeline_sheet.cell_value(87, 5) ==True:
            self.conf['tgs_pipeline']['Species_Annotation']['enable'] = True 
        if tgspipeline_sheet.cell_value(89, 5) ==True:
            self.conf['tgs_pipeline']['Species_Annotation']['Kraken2']['enable'] = True 
        if tgspipeline_sheet.cell_value(90, 5) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['Kraken2']['--quick'] = tgspipeline_sheet.cell_value(90, 5) 
        if tgspipeline_sheet.cell_value(91, 5) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['Kraken2']['--minimum-hit-groups'] = str(int(tgspipeline_sheet.cell_value(91, 5)))
        if tgspipeline_sheet.cell_value(92, 5) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['Kraken2']['--confidence'] = tgspipeline_sheet.cell_value(92, 5)
        if tgspipeline_sheet.cell_value(93, 5) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['Kraken2']['--minimum-base-quality'] = str(int(tgspipeline_sheet.cell_value(93, 5)))
        
        if tgspipeline_sheet.cell_value(89, 7) ==True:
            self.conf['tgs_pipeline']['Species_Annotation']['MetaOthello']['enable'] = True 
        if tgspipeline_sheet.cell_value(90, 7) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaOthello']['Kmer_length'] = str(int(tgspipeline_sheet.cell_value(90, 7)))
        
        if tgspipeline_sheet.cell_value(89, 9) ==True:
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['enable'] = True 
        if tgspipeline_sheet.cell_value(90, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--input_type'] = tgspipeline_sheet.cell_value(90, 9) 
        if tgspipeline_sheet.cell_value(91, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--bt2_ps'] = tgspipeline_sheet.cell_value(91, 9) 
        if tgspipeline_sheet.cell_value(92, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--tax_lev'] = tgspipeline_sheet.cell_value(92, 9) 
        if tgspipeline_sheet.cell_value(93, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--min_cu_len'] = str(int(tgspipeline_sheet.cell_value(93, 9)))
        if tgspipeline_sheet.cell_value(94, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--min_alignment_len'] = str(int(tgspipeline_sheet.cell_value(94, 9)))
        if tgspipeline_sheet.cell_value(95, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--ignore_viruses'] = tgspipeline_sheet.cell_value(95, 9) 
        if tgspipeline_sheet.cell_value(96, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--ignore_eukaryotes'] = tgspipeline_sheet.cell_value(96, 9) 
        if tgspipeline_sheet.cell_value(97, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--ignore_bacteria'] = tgspipeline_sheet.cell_value(97, 9) 
        if tgspipeline_sheet.cell_value(98, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--ignore_archaea'] = tgspipeline_sheet.cell_value(98, 9) 
        if tgspipeline_sheet.cell_value(99, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--avoid_disqm'] = tgspipeline_sheet.cell_value(99, 9) 
        if tgspipeline_sheet.cell_value(100, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--no_map'] = tgspipeline_sheet.cell_value(100, 9) 
        if tgspipeline_sheet.cell_value(101, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--stat_q'] = tgspipeline_sheet.cell_value(101, 9) 
        if tgspipeline_sheet.cell_value(102, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--ignore_markers'] = tgspipeline_sheet.cell_value(102, 9) 
        if tgspipeline_sheet.cell_value(103, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--stat'] = tgspipeline_sheet.cell_value(103, 9) 
        if tgspipeline_sheet.cell_value(104, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['-t'] = tgspipeline_sheet.cell_value(104, 9) 
        if tgspipeline_sheet.cell_value(105, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--nreads'] = str(int(tgspipeline_sheet.cell_value(105, 9)))
        if tgspipeline_sheet.cell_value(106, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--pres_th'] = tgspipeline_sheet.cell_value(106, 9) 
        if tgspipeline_sheet.cell_value(107, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--clade'] = tgspipeline_sheet.cell_value(107, 9) 
        if tgspipeline_sheet.cell_value(108, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--min_ab'] = tgspipeline_sheet.cell_value(108, 9) 
        if tgspipeline_sheet.cell_value(109, 9) != '':
            self.conf['tgs_pipeline']['Species_Annotation']['MetaPhlAn3']['--read_min_len'] = str(int(tgspipeline_sheet.cell_value(109, 9)))
        
        if tgspipeline_sheet.cell_value(87, 1) ==True:
            self.conf['tgs_pipeline']['gene_predition']['enable'] = True 
        if tgspipeline_sheet.cell_value(89, 1) ==True:
            self.conf['tgs_pipeline']['gene_predition']['prodigal']['enable'] = True 
        if tgspipeline_sheet.cell_value(90, 1) != '':
            self.conf['tgs_pipeline']['gene_predition']['prodigal']['-c'] = tgspipeline_sheet.cell_value(90, 1) 
        if tgspipeline_sheet.cell_value(91, 1) != '':
            self.conf['tgs_pipeline']['gene_predition']['prodigal']['-m'] = str(int(tgspipeline_sheet.cell_value(91, 1)))
        if tgspipeline_sheet.cell_value(92, 1) != '':
            self.conf['tgs_pipeline']['gene_predition']['prodigal']['-n'] = tgspipeline_sheet.cell_value(92, 1) 
        if tgspipeline_sheet.cell_value(93, 1) != '':
            self.conf['tgs_pipeline']['gene_predition']['prodigal']['-s'] = tgspipeline_sheet.cell_value(93, 1) 
        if tgspipeline_sheet.cell_value(94, 1) != '':
            self.conf['tgs_pipeline']['gene_predition']['prodigal']['-t'] = tgspipeline_sheet.cell_value(94, 1) 
        if tgspipeline_sheet.cell_value(95, 1) != '':
            self.conf['tgs_pipeline']['gene_predition']['prodigal']['-f'] = tgspipeline_sheet.cell_value(95, 1) 
        if tgspipeline_sheet.cell_value(96, 1) != '':
            self.conf['tgs_pipeline']['gene_predition']['prodigal']['-g'] = str(int(tgspipeline_sheet.cell_value(96, 1)))
        if tgspipeline_sheet.cell_value(97, 1) != '':
            self.conf['tgs_pipeline']['gene_predition']['prodigal']['-p'] = tgspipeline_sheet.cell_value(97, 1) 
                
        if tgspipeline_sheet.cell_value(89, 3) ==True:
            self.conf['tgs_pipeline']['gene_predition']['metagenemark']['enable'] = True 
        if tgspipeline_sheet.cell_value(90, 3) != '':
            self.conf['tgs_pipeline']['gene_predition']['metagenemark']['-f'] = tgspipeline_sheet.cell_value(90, 3) 
        if tgspipeline_sheet.cell_value(91, 3) != '':
            self.conf['tgs_pipeline']['gene_predition']['metagenemark']['-K'] = tgspipeline_sheet.cell_value(91, 3) 
        if tgspipeline_sheet.cell_value(92, 3) != '':
            self.conf['tgs_pipeline']['gene_predition']['metagenemark']['-r'] = tgspipeline_sheet.cell_value(92, 3) 
        if tgspipeline_sheet.cell_value(93, 3) != '':
            self.conf['tgs_pipeline']['gene_predition']['metagenemark']['-c'] = tgspipeline_sheet.cell_value(93, 3) 
        if tgspipeline_sheet.cell_value(94, 3) != '':
            self.conf['tgs_pipeline']['gene_predition']['metagenemark']['-s'] = tgspipeline_sheet.cell_value(94, 3) 
        if tgspipeline_sheet.cell_value(95, 3) != '':
            self.conf['tgs_pipeline']['gene_predition']['metagenemark']['-p'] = str(int(tgspipeline_sheet.cell_value(95, 3)))
        if tgspipeline_sheet.cell_value(96, 3) != '':
            self.conf['tgs_pipeline']['gene_predition']['metagenemark']['-e'] = tgspipeline_sheet.cell_value(96, 3) 
        if tgspipeline_sheet.cell_value(97, 3) != '':
            self.conf['tgs_pipeline']['gene_predition']['metagenemark']['-g'] = str(int(tgspipeline_sheet.cell_value(97, 3)))
        
        if tgspipeline_sheet.cell_value(110, 1) ==True:
            self.conf['tgs_pipeline']['functional_annotation']['enable'] = True 
        if tgspipeline_sheet.cell_value(112, 1) ==True:
            self.conf['tgs_pipeline']['functional_annotation']['emapper.py']['enable'] = True 
        if tgspipeline_sheet.cell_value(113, 1) != '':
            self.conf['tgs_pipeline']['functional_annotation']['emapper.py']['--matrix'] = tgspipeline_sheet.cell_value(113, 1) 
        if tgspipeline_sheet.cell_value(114, 1) != '':
            self.conf['tgs_pipeline']['functional_annotation']['emapper.py']['--gapopen'] = str(int(tgspipeline_sheet.cell_value(114, 1)))
        if tgspipeline_sheet.cell_value(115, 1) != '':
            self.conf['tgs_pipeline']['functional_annotation']['emapper.py']['--gapextend'] = str(int(tgspipeline_sheet.cell_value(115, 1)))
        if tgspipeline_sheet.cell_value(116, 1) != '':
            self.conf['tgs_pipeline']['functional_annotation']['emapper.py']['--query-cover'] = tgspipeline_sheet.cell_value(116, 1) 
        if tgspipeline_sheet.cell_value(117, 1) != '':
            self.conf['tgs_pipeline']['functional_annotation']['emapper.py']['--subject-cover'] = tgspipeline_sheet.cell_value(117, 1) 
        if tgspipeline_sheet.cell_value(118, 1) != '':
            self.conf['tgs_pipeline']['functional_annotation']['emapper.py']['--seed_ortholog_evalue'] = tgspipeline_sheet.cell_value(118, 1) 
        if tgspipeline_sheet.cell_value(119, 1) != '':
            self.conf['tgs_pipeline']['functional_annotation']['emapper.py']['--seed_ortholog_score'] = tgspipeline_sheet.cell_value(119, 1) 
        if tgspipeline_sheet.cell_value(120, 1) != '':
            self.conf['tgs_pipeline']['functional_annotation']['emapper.py']['--target_taxa'] = tgspipeline_sheet.cell_value(120, 1) 
        if tgspipeline_sheet.cell_value(121, 1) != '':
            self.conf['tgs_pipeline']['functional_annotation']['emapper.py']['--predict_output_format'] = tgspipeline_sheet.cell_value(121, 1) 
        if tgspipeline_sheet.cell_value(111, 3) == True:
            self.conf['tgs_pipeline']['functional_annotation']['PHI_Annotation']['enable'] = True 
        if tgspipeline_sheet.cell_value(112, 3) == True:
            self.conf['tgs_pipeline']['functional_annotation']['VFDB_Annotation']['enable'] = True 
        if tgspipeline_sheet.cell_value(113, 3) == True:
            self.conf['tgs_pipeline']['functional_annotation']['CARD_Annotation']['enable'] = True 
        if tgspipeline_sheet.cell_value(114, 3) == True:
            self.conf['tgs_pipeline']['functional_annotation']['TCDB_Annotation']['enable'] = True 
        if tgspipeline_sheet.cell_value(115, 3) != '':
            self.conf['tgs_pipeline']['functional_annotation']['PHI_Annotation']['plot_for_top_k'] = tgspipeline_sheet.cell_value(115, 3)
        if tgspipeline_sheet.cell_value(116, 3) != '':
            self.conf['tgs_pipeline']['functional_annotation']['VFDB_Annotation']['plot_for_top_k'] = tgspipeline_sheet.cell_value(116, 3)
        if tgspipeline_sheet.cell_value(117, 3) != '':
            self.conf['tgs_pipeline']['functional_annotation']['CARD_Annotation']['plot_for_top_k'] = tgspipeline_sheet.cell_value(117, 3)
        if tgspipeline_sheet.cell_value(118, 3) != '':
            self.conf['tgs_pipeline']['functional_annotation']['TCDB_Annotation']['plot_for_top_k'] = tgspipeline_sheet.cell_value(118, 3)
        if tgspipeline_sheet.cell_value(112, 5) == True:
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['enable'] = True 
        if tgspipeline_sheet.cell_value(113, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-evalue'] = tgspipeline_sheet.cell_value(113, 5) 
        if tgspipeline_sheet.cell_value(114, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-word_size'] = str(int(tgspipeline_sheet.cell_value(114, 5)))
        if tgspipeline_sheet.cell_value(115, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-gapopen'] = str(int(tgspipeline_sheet.cell_value(115, 5))) 
        if tgspipeline_sheet.cell_value(116, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-gapextend'] = str(int(tgspipeline_sheet.cell_value(116, 5))) 
        if tgspipeline_sheet.cell_value(117, 5) != '':
            i = ngspipeline_sheet.cell_value(117, 5)
            if isinstance(i,float):
                i = int(i)
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-comp_based_stats'] = i
        if tgspipeline_sheet.cell_value(118, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-seg'] = tgspipeline_sheet.cell_value(118, 5) 
        if tgspipeline_sheet.cell_value(119, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-qcov_hsp_perc'] = tgspipeline_sheet.cell_value(119, 5) 
        if tgspipeline_sheet.cell_value(120, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-max_hsps'] = str(int(tgspipeline_sheet.cell_value(120, 5)))
        if tgspipeline_sheet.cell_value(121, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-culling_limit'] = str(int(tgspipeline_sheet.cell_value(121, 5)))
        if tgspipeline_sheet.cell_value(122, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-best_hit_overhang'] = tgspipeline_sheet.cell_value(122, 5) 
        if tgspipeline_sheet.cell_value(123, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-best_hit_score_edge'] = tgspipeline_sheet.cell_value(123, 5) 
        if tgspipeline_sheet.cell_value(124, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-max_target_seqs'] = str(int(tgspipeline_sheet.cell_value(124, 5)))
        if tgspipeline_sheet.cell_value(125, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-xdrop_ungap'] = tgspipeline_sheet.cell_value(125, 5) 
        if tgspipeline_sheet.cell_value(126, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-xdrop_gap'] = tgspipeline_sheet.cell_value(126, 5) 
        if tgspipeline_sheet.cell_value(127, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-xdrop_gap_final'] = tgspipeline_sheet.cell_value(127,5) 
        if tgspipeline_sheet.cell_value(128, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-window_size'] = str(int(tgspipeline_sheet.cell_value(128, 5)))
        if tgspipeline_sheet.cell_value(129, 5) != '':
            self.conf['tgs_pipeline']['functional_annotation']['blastp']['-ungapped'] = tgspipeline_sheet.cell_value(129, 5) 
        
        if tgspipeline_sheet.cell_value(112, 7) ==True:
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['enable'] = True 
        if tgspipeline_sheet.cell_value(113, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--max-target-seqs'] = str(int(tgspipeline_sheet.cell_value(113, 7)))
        if tgspipeline_sheet.cell_value(114, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--top'] = tgspipeline_sheet.cell_value(114, 7) 
        if tgspipeline_sheet.cell_value(115, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--range-culling'] = tgspipeline_sheet.cell_value(115, 7) 
        if tgspipeline_sheet.cell_value(116, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--evalue'] = tgspipeline_sheet.cell_value(116, 7) 
        if tgspipeline_sheet.cell_value(117, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--min-score'] = tgspipeline_sheet.cell_value(117, 7) 
        if tgspipeline_sheet.cell_value(118, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--id'] = tgspipeline_sheet.cell_value(118, 7) 
        if tgspipeline_sheet.cell_value(119, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--query-cover'] = tgspipeline_sheet.cell_value(119, 7) 
        if tgspipeline_sheet.cell_value(120, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--subject-cover'] = tgspipeline_sheet.cell_value(120, 7) 
        if tgspipeline_sheet.cell_value(121, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--sensitive'] = tgspipeline_sheet.cell_value(121, 7) 
        if tgspipeline_sheet.cell_value(122, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--more-sensitive'] = tgspipeline_sheet.cell_value(122, 7) 
        if tgspipeline_sheet.cell_value(123, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--block-size'] = tgspipeline_sheet.cell_value(123, 7) 
        if tgspipeline_sheet.cell_value(124, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--index-chunks'] = str(int(tgspipeline_sheet.cell_value(124, 7)))
        if tgspipeline_sheet.cell_value(125, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--gapopen'] = str(int(tgspipeline_sheet.cell_value(125, 7)))
        if tgspipeline_sheet.cell_value(126, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--gapextend'] = str(int(tgspipeline_sheet.cell_value(126, 7))) 
        if tgspipeline_sheet.cell_value(127, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--matrix'] = tgspipeline_sheet.cell_value(127, 7) 
        if tgspipeline_sheet.cell_value(128, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--comp-based-stats'] = str(int(tgspipeline_sheet.cell_value(128, 7)))
        if tgspipeline_sheet.cell_value(129, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--masking'] = str(int(tgspipeline_sheet.cell_value(129, 7)))
        if tgspipeline_sheet.cell_value(130, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--no-self-hits'] = tgspipeline_sheet.cell_value(130, 7) 
        if tgspipeline_sheet.cell_value(131, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--sallseqid'] = tgspipeline_sheet.cell_value(131, 7) 
        if tgspipeline_sheet.cell_value(132, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--algo'] = str(int(tgspipeline_sheet.cell_value(132, 7))) 
        if tgspipeline_sheet.cell_value(133, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--bin'] = str(int(tgspipeline_sheet.cell_value(133, 7))) 
        if tgspipeline_sheet.cell_value(134, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--min-orf'] = str(int(tgspipeline_sheet.cell_value(134, 7))) 
        if tgspipeline_sheet.cell_value(135, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--freq-sd'] = str(int(tgspipeline_sheet.cell_value(135, 7))) 
        if tgspipeline_sheet.cell_value(136, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--id2'] = str(int(tgspipeline_sheet.cell_value(136, 7))) 
        if tgspipeline_sheet.cell_value(137, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--window'] = str(int(tgspipeline_sheet.cell_value(137, 7))) 
        if tgspipeline_sheet.cell_value(138, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--xdrop'] = tgspipeline_sheet.cell_value(138, 7) 
        if tgspipeline_sheet.cell_value(139, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--ungapped-score'] = tgspipeline_sheet.cell_value(139, 7) 
        if tgspipeline_sheet.cell_value(140, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--band'] = tgspipeline_sheet.cell_value(140, 7) 
        if tgspipeline_sheet.cell_value(141, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--shapes'] = str(int(tgspipeline_sheet.cell_value(141, 7)))
        if tgspipeline_sheet.cell_value(142, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--shape-mask'] = tgspipeline_sheet.cell_value(142, 7) 
        if tgspipeline_sheet.cell_value(143, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--culling-overlap'] = tgspipeline_sheet.cell_value(143, 7) 
        if tgspipeline_sheet.cell_value(144, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--range-cover'] = tgspipeline_sheet.cell_value(144, 7) 
        if tgspipeline_sheet.cell_value(145, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--no-auto-append'] = tgspipeline_sheet.cell_value(145, 7) 
        if tgspipeline_sheet.cell_value(146, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--stop-match-score'] = tgspipeline_sheet.cell_value(146, 7) 
        if tgspipeline_sheet.cell_value(147, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--tantan-minMaskProb'] = tgspipeline_sheet.cell_value(147, 7) 
        if tgspipeline_sheet.cell_value(148, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--daa'] = tgspipeline_sheet.cell_value(148, 7) 
        if tgspipeline_sheet.cell_value(149, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--forwardonly'] = tgspipeline_sheet.cell_value(149, 7) 
        if tgspipeline_sheet.cell_value(150, 7) != '':
            self.conf['tgs_pipeline']['functional_annotation']['diamond']['--seq'] = str(int(tgspipeline_sheet.cell_value(150, 7))) 
       
        
        
        
        
        
        
        
        
        
        